sudo: required
dist: trusty

sudo: required

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - chmod +x mvnw

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "VHF9fd/t7y02509cuKn4DmJG0ldi7VTVr9k4m01rJ8UDsBhxuElhfYDhMujwtwztBZuriN22im1lnUaAu1vCkXuBtmra1nl/9quktDJeHelJa6YYG/dLyOv5S6Kyn+Mu+1k4Y1rLUlUlMnBhC+atND15QEF9C3hvQKqUI/mCDY3ZvVQseO4KTk3XxBeCT74g45QkXLzZia3UGcLQZcDutNo4mEQBOtRSDRdU4Fcct8hv6KmyaOjEib+Z/pwWWOOxQFqOoypUQj05mZiT2YxZ6uHlqd9VAihgQ+EZNTNT4pqywOcMR+zjJ2QfmBmzMd1hk2ifUSzBaljomLFE2UHj7Oi9PnqZpuC1yMIwQJ7yAcKXumVp8pkvhu3g2tze8CH8lEThCOpl+XaZrKt4+3RMKWHDi+Yphk4+JG2innbWar0xNH1tt3i0nUuLWSOVJgcIz3PKke3+8KWtSYI+I6r+I3ByhqkMoEzyez/6jqHEA9T0/gnFXcjEoouBD7nOz+XDL1hPRSzyqiqv1xMNew5LkCXJNz/2V93wEGHhj4SyiFY13CMIMM2FAzZxgLyJvxfrn7OmtX0NauC+ocAcjRR+fgvMWcU5bt3/m9zRDf+AmsEm6HIjBNN2B9kIUIjUEiLsQV2GoiRo3sB5nA5dTdV2eoFAWcZ1XITc9z259hwsSss="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=XXX --add
  - secure: "WOoxmAMdb/kMrRqnsGKvkpmyR7mD7+TAwuEXBfWH5Gmautksq9DiXLpkMyw/ktG6kBTmOa9O9bl2Ge/IRwoJPpQ+q6Hw4K9xvzhmFV06VE1Ip5y6YkbxcTzHYGSW/6w+rvHAv8BXl3sQzLaaJ+mgsBWCq+ehponeAfb6DqtMQPmhA8iiU0n9R+cxTd9f9PnRB+tQ98nQH/nicMa8WQx9VvtklDr6ewCTdxIeICKrQkWuUMfrSnPBVDnBYWMG6Jgguo1pJeT8Ju57CtyiFVLbfy/GU5RBU6JAWARbbuIOpwpYZWj9sdtifZJJXkM8caN0siGUsv9fzTOZ9xYJQV89EkYxb0TBhnuX9fdGngmGIoCeEh7kzUDlCnfcC1i/i4y27LjbiMMBZBYgMREP2iziufneBI/0E2CFii9XTidfH4pBTSo6JjrtTcf5QkhxwWmMtCePG4BaYzCyaVWZY/qBlAc8zQEVfBH8705BiW+vE+WWQEGhW/vlC9xovdQVseRUOUxhtS39jmFGXyT1oSLNH+zWANmY6a/VkurxCojT3nVxeF/5wEh7uM+s/n/zWXNvzQYdRg4ElpEepQkdJNMxGT/rZkLjOq3HmhQIP4Qn5ZM+x0VLZg8xxh5Ya1fqRQFMmaN9Zksaxc1VDTREST4UScoLh0/13XfUIxJ4cYMuDsk="
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX --add
  - secure: "WM3dqRqxJQIfaY+dgh6QgT20M9iNaQRXcl5DKKtarIIF4LDptk6XmxrjvojZl+Z64P/oHIsHM4D5k5ZnSwrvHl2FdJo+I7XMfzxdAmSbCMnXreiBYCuigFyRxOUrQaQ9RDBl/W8oCa2o6UGx/R/qLFZBn0NFw5KeaCI1TxUulJvYgy38WvJJAKI8Wb+/O00+XvDqhcWtkw0ZcxsxkXuFF36bC+D5HkT9113ZI5OQWX4PMhIHrOMZoDwJAmOpZE0P/TH61WI/fZSpoCH1LPrYDZz1QS1INGX+UQF3CRLG8Xjw/w6rnAVAR/gRfUhclqCow7KBXjuD2QmtAkvgEDrxHcBZHMoiwbMBR4uPSRRyALCr6mmG7DQZQEdoSM3jjDGMy+XMinONLgHbnqh5bs8eU0HHqgDjcB3+zmVRN7qMFDyKObxbWbEjQvo7JljyAOtubvgD9VJrq6Pt5umKvVoEyFfyqXkPTPjHCK8Al6bPjzifKxx9fvWx3uFQ5dGqoaRcLFtFFHebBzpC/W4HFBupr0trIZq50zGJ7v1XAlCgKZWwJIywTchLQ0wwkCKK4DgulhEgnHsPMTV//mEPzsSZgix64dTpbx5bYzEQLP79j5o8juq+F+MQEarB0s3WgS1Mft8NAZa6psxX8u6uEupE+RPr3by/DK2CJ8B46xwX3UE="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "PmO5ZCpB73dYaSrb3ZC1YvfO7SF0PGCf1t7EeaS/4ZPgSJE7bw01xjo/jcL0zJQz9WmGsKpw8WYobVssnYvpm4AC4DmTa63kKE7e3wZOx4250pAOkJ/nMhpHSOUDdUk3UQBAYnQ1y/bDVf8j8FKMvfdEbkSXTrYe2ZKOGlqAMYZl2OiKXBKwXino4jJn3sOBx+JaFdzuqzEPhkjVpq/hhP33I3rgn9WaMmGYZiOlnGzHBVezaHufO92VFMgtnSjmZ1A3S2IgszzL8ab2d4Wj4Pvhbg1saPuf3eeDJM/VmXg93V4G55Zr9JC35ov0vTKJz0W/XSZi4g1rkweOfReCkz3NT+9YuN0xnQI4f64MG7Mw/l7ZsrgcpMO5SiK0oWZujQqbMy1jtOrKeJLsmTJZE138E8m9qhlcibQWX1J+frYtakWAoAf8lRQUtuKOh4k7oWObveNBZG0qp6/RBHr4nBJjMRvps62wRbRZ57pfYBFYgjYijCpSa7ISlj5oCABW7jtzTW8qvLqfSXlgPicrQ9/IBy6ML1kVNtYvV8xghS5vLlSZ0g7mHwDnvJ4zTLlt6/pdTSjPdjTt6YEvVivAZRfOIS9YkejcyD3NhlvSZkLyMLzSwiXjkICPAyTWyBUfgaURdqymfSIMp7QPu9AM9gVqn0r+wd+DSAR3GqCtEG4="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "yN3S38VTM4uMEgFs6Sy8Tftf3fHaRVo282Izv+/HwgbbFiL22XG5D/ft+qIt40YvqnvXbIwBilH6S9rEk4kZ5PH2KIA+iN7QSbfkHWryJShD6rNdunwzqzDzbCMMkm6WDE1QYy+DNFZ2sl9cL1sBEHPjBUzeT0PaNTRIOngKdqTmJsE4uGN+HOxYb+DDMl3m7qMu1kDntJJu8YzUhUDOg23FkY2KgNY0CulGkpXx3e8OSLT8G7FqiowOEnjEIy1uARn6ob8UWQKUrrFs4v2z6ATBjKWFe7sNadipDiQv5oVwrseWhOmThLmBiyGiFJyAO+uFW0qGXSNUKmMi2jQipNjButV0s0Evfwv8r/Xqc0bpVgHorp68S/9ii8F6/R6qV4BK9hW/trj0kBlnWRBChj4hwQ0er6BKIvAsLDMG4zlUh/RwK89a84JlDDu5nUhc/ujUmfzI1V1KhC4Eble7gr8eIalEmfa3X4y4PkH7C870DSTb+uttJY4gEiE4RuXiWXzir7Gm4urlhTcyVJMHT8u5Z1h9wyBdG8e/5Csoky1CpRNc/RACaDOpsLN0U+V7jxa0kwS7RjPH3cXSl5JX3+765F8Ozb2JKfkd+nXh5DrquuZzjoCJBYUhDAbQN0ENnx9XMoHU8XSbMzcn9HV21z4DP1W1xX4Dlfpu+UYDivM="
