sudo: required
dist: trusty

services:
  - docker

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - chmod +x mvnw

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt -r org/repo BINTRAY_USER=your_github_account
  - secure: "GWikYLWt/rqnWkh4qcCN5r3rVO8fYCzPmvfSpzMD30o6RirC7c/ZMIRs0MF1DyXLB8zCjjwbth+2VeeV0XFcz2lfl5p/DiSTqqK64u1Mo2bxcQKDa8fp7GJHtA0OrJkMYMR9RtQpHFjplsXAXk9CkXLUe130WhRPqnT6mDs2rK7rbzVOqyG5lsLnhQhg06Z4qLGkjzEiouh5N58uUot9mMyAsoLD6Qk8ZNjvEgr+ewZvvWPPxltRJ61XRDcJ3H4FB8y+/znUbUxlI8YU3EtWFh1ywZwyz1PKsJVVTWZ9AcLReisw4lhgG+awz2kMq2UUtGG0ejM1dVzk2jWBQgUne4DEzGAs+a6XQGUT5k7LPhxVcrc3NJNRdYBvjLKNtcPPFObAvCLBuFR32NIanrHepL67x9+nfZwv+O0vsEybGaVSWeWVf9/REMfib9AzdjRSeZhfKUr+zKHGWjidVCeUGInTLeuZcSlYTWvXVmSaVDoMpJaMVxyGH/vShhqJ8rdSxHMiy6r9f3oc1tox5shG3IQ6/bZYQQwnUMsKu7P+J3h/wkweBmIugA7XpyXC2Ejri9MgM5WdmTQgBhdTFZiMDvkIBsMjTV8GlNiasqHnc/krdE7993Ic1M0eFew4BcxJZhLGmoARNcIpJ9r5w2i5q/Orf+hlkE7FPhaLsB+DbZk="
  # Ex. travis encrypt -r org/repo BINTRAY_KEY=XXX --add
  - secure: "zj9fJ5shI9ie5biwUyllV1lJR3u2oimF8lqIPOU8dgYgKVfZAvjmbk4EuZ822yyNg8rAlPOUMAVpPsUXs4MmnPX/oOWrIuFiVh7sjtgPD+ud4BK9Xmt2IjQ4EXEMcW7Z9KVfTDitViZH6qzr/L3DY2OVKuMzM8zhmLLfqRk7P2UuMtHi/XhNSpyYUjfyHqmK7qqSxPJILrbZOgQrxrqrnAAHAScszbcJSbR/lC+TBl1Y6vvW617VmzPduKTJ/Kd55R+qD6X+ZeDDAHuMFD6vLcW2iJoIPy8EwpRI44xEuOyub5HzUtUjwha1fOr0j3QYL7fRncAH3iQj1mkTPVHzgjAoS7h6VbS0RgPIxDjB2zO2GCqbSmMmRB61+hCxTVXS0OBf5A1M6Cquep68erbjgRbJs+PAwodovPRW4Oo5ieyeoXBIHLBbwrADHcd68Vx8jyOj301LMHx2IybddMSjJhSsJqocgB+QLbrPp0EZHKNO5Hwt7P2u7BedlCfjll0slviwswLn4GDo3ZFimGOqzp8c63gsQonYCQEaj4C4QfY0R3yptCRZojNCQfGIEKGQUmLD9F5I20q3xxis04AcONoxBHRLksa8Kd1o1MdU98wUPp8xVR9GcLNA1WijzwXvylGpOkNlcEOmeZdOizgyper3ocFQNcTgFc62gvVcVgg="
  # Ex. travis encrypt -r org/repo GH_TOKEN=XXX --add
  - secure: "nBNbp8BZe9gxQAkgpKy/9ruYE63wLl9RaFYizaztuO1/GaWZHeOVsUOgiV4FX3LNC+YoesdQuSlpHKe0gkFHsjuulsFhMN2A+tB4gzjDJ7GZgiK/a89fB1D7u9ZsrmuCJhxNEHmX43HUpvE5wO20sXebIaC/PzclnC3ooP2Pmv1ltQ35Glzp5XgZDDuHyFcGoth6BOcJIAIhKpzZZlmXKOr8frciitLinuvx5Fh1z6Ij6FqFkD/MiPOoU8ZFDNQgDFLrR7nkQVpOf6j/sPKehHCy6EDm4+/Xny6YtnFhuAmBcnJNsy3LtltwZTinHjDUETbnqLBKTYUiZwYmycozSqU7dawsZQi7NG9XelFQ+AhQWYpnfT4odvhX183OezZRmxOtb4ZDkPdPFI/EfjWNPZ5f7r5E8YjfwHwUxWJ7GarQ2w3isAN/a53AIRSfGFvw6ZNds59kU1ZwEB8p0WxWrZZiDmjpr2+ztZb0O/KLtygRppcFXPfy8nieBFBP6oT0W6Yv5XHGmRm1AHtz2/DLG3/mkdrBJLpbscmOdUKSDiUwk8sRRg+b0/Ob1vIS51MNON06iC5KNM2+VC8FtA2SlAusIdCddg04QCeSEmTWbmWFe4RZzY/++bz1jHIYBRWcgFjH4MWqe/t1iPsOfcnrR5mqyDa1S0qThsyY63XYbYQ="
  # Ex. travis encrypt -r org/repo SONATYPE_USER=your_sonatype_account
  - secure: "r01AKpO6CJkfIJLajMymZ1HiW8i/LIDGpKyT3vRhKBgxlcwofbZ8WSNuLUMVLLrpWniWmJGB3Ah7CWl/WDSLe6yvpln+ytZTZSWmiz7u8Cb3T6rTmNecw/2xiBPxsqLB57POq0gnfnrhethR1EKVNEExSgxFUo2vFoZWIjwdNDm0PV4OEJc8J/1LdpGFlMOqsRddfQwewofcbB7WuKhK4mKT1U5oG4ypMVVVgVdt5a8r/ig4aE591uDA+2ZBZ+jXkuGe+XcILeU12leWSF/MWRTCkxma7BnluNTp1ZcRJNavMtKfzMSVAKeepVu+IrRyys9V8mZec3C3vGD+tjU1JeEBGxoYz1wdntqD16N+MMhebWq9GUuZDMRhnGcaoOJ07Sz8B7bmGwSnC6G3pdobca6mQiDj6L8QQqIYlQf47WmIzMeSlUz6n2H4PAA/xRSzfpjV60/v3oINFKYNC1hy4JPyw77lEwM4OeJhHjVdu8DBH+pYNCR9SfLbj4bcc8CZXkitKhGjJk1ucjW1pQTyhlZXpTbHpqTtGnPRmF62l6zwcT8LCwTC3u7khNAXwpOM8QAtFc5Xj4T6nitP15r53fHHU+HLzhcdoLsg3BXaqopSA24TlAFCtL3QWRqDyDagU05qVq31I9TtG3/HvQlAqpHvRQmr5MOs4cfs1ieK1O4="
  # Ex. travis encrypt -r org/repo SONATYPE_PASSWORD=your_sonatype_password
  - secure: "X1UdUS6JEfyUVo66U2xF7VR1DrbcdWh72DTEYH7iBAtKyTDFRLe5KZi8Pyczzsf9W54/fqR508tIkwTQzNeB/E5IeLsHUUP7hiV1UD8eX6d5nHRiVcvmxCP3BD/9k5Q8S583Py0W6cSL1hfWU4v01tSKuLcQfsV8By2Wyb2DjL88KxUe/Z4T34VxP5ddTd0Tgrl4naryrbhDNIsDeXIofkv1c9laL7J1AQ9o1GGXCLWJBOFcXRJHPPO/79uV8iHxW9hD7japEUr1VQzHxZQpgL/TUdHpQ2li7kauigrqJNPC/1DJzoMl3/o3xh+2lBSHOBmmwsbMx8uDootYI5vBVe8szqhEg/txzF3U6QpTbJf7ezhbE59JQ5yGfXxaEkSZAEX/Bt8//+Xc7hI78Ch2sLwVFHvYr3MO6W6f8/CAZvbiM7mKDC7ehwQDK4SzT6UeY2iK/k/HkstKhYsIbYRbC5ZL9Ds62vwRTC0rtHYLcMNjHkWSNIukWPh1oayCGxEHD2/YqiaQnCSAijrwW+klu2iGtHwulzHmF0BIENR1VK4DdhfiBr1GZ+zgAP//ZFJcGA3dTawDfOI5aQ9aCl1/jHZxknnwp+CrF0WQcNe817X84U8FpM2p0cF1y9uDZGDiLRw4cFmvUPeSwrE3yFELRTZ2cwHadRHO7z130hWCmnM="
